export { TerminalDetectedShells } from './terminal-detected-shells';
export { TerminalProfileList } from './terminal-profile-list';
export { TerminalProfileDialog } from './terminal-profile-dialog';
export { TerminalPsManagement } from './terminal-ps-management';
export { TerminalPsModulesTable } from './terminal-ps-modules-table';
export { TerminalShellConfig } from './terminal-shell-config';
export { TerminalShellFramework } from './terminal-shell-framework';
export { TerminalProxySettings } from './terminal-proxy-settings';
export { TerminalEnvVars } from './terminal-env-vars';
export { TerminalTemplatePicker } from './terminal-template-picker';
export { TerminalNav, TERMINAL_SECTIONS } from './terminal-nav';
export type { TerminalSection, TerminalSectionDef } from './terminal-nav';
export { TerminalQuickStatus } from './terminal-quick-status';
export { getShellIcon } from './shared/shell-icon';
export { ShellEnvironmentSection } from './sections/shell-environment-section';
export { ProfilesSection } from './sections/profiles-section';
export { ConfigurationSection } from './sections/configuration-section';
export { NetworkSection } from './sections/network-section';
