use crate::error::{CogniaError, CogniaResult};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

/// Configuration for scaffolding a new plugin project
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ScaffoldConfig {
    pub name: String,
    pub id: String,
    pub description: String,
    pub author: String,
    pub output_dir: String,
    #[serde(default)]
    pub license: Option<String>,
    #[serde(default)]
    pub repository: Option<String>,
    #[serde(default)]
    pub homepage: Option<String>,
    #[serde(default = "default_language")]
    pub language: PluginLanguage,
    #[serde(default)]
    pub permissions: ScaffoldPermissions,
    #[serde(default)]
    pub include_ci: bool,
    #[serde(default = "default_include_vscode")]
    pub include_vscode: bool,
    #[serde(default)]
    pub additional_keywords: Vec<String>,
}

fn default_language() -> PluginLanguage {
    PluginLanguage::Rust
}

fn default_include_vscode() -> bool {
    true
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct ScaffoldPermissions {
    #[serde(default)]
    pub config_read: bool,
    #[serde(default)]
    pub env_read: bool,
    #[serde(default)]
    pub pkg_search: bool,
    #[serde(default)]
    pub clipboard: bool,
    #[serde(default)]
    pub notification: bool,
    #[serde(default)]
    pub http: Vec<String>,
    #[serde(default)]
    pub fs_read: bool,
    #[serde(default)]
    pub fs_write: bool,
    #[serde(default)]
    pub process_exec: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum PluginLanguage {
    Rust,
    JavaScript,
    TypeScript,
}

impl Default for PluginLanguage {
    fn default() -> Self {
        Self::Rust
    }
}

/// Result of scaffold operation
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ScaffoldResult {
    pub plugin_dir: String,
    pub files_created: Vec<String>,
}

/// Result of plugin validation
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ValidationResult {
    pub valid: bool,
    pub errors: Vec<String>,
    pub warnings: Vec<String>,
}

/// Generate a new plugin project from a ScaffoldConfig
pub async fn scaffold_plugin(config: &ScaffoldConfig) -> CogniaResult<ScaffoldResult> {
    validate_scaffold_config(config)?;

    let output = PathBuf::from(config.output_dir.trim());
    let plugin_dir = output.join(config.id.trim());

    if plugin_dir.exists() {
        return Err(CogniaError::Plugin(format!(
            "Directory already exists: {}",
            plugin_dir.display()
        )));
    }

    tokio::fs::create_dir_all(&plugin_dir)
        .await
        .map_err(|e| CogniaError::Plugin(format!("Failed to create plugin directory: {}", e)))?;

    let mut files_created = Vec::new();

    // Generate plugin.toml
    let manifest = generate_manifest(config);
    let manifest_path = plugin_dir.join("plugin.toml");
    tokio::fs::write(&manifest_path, &manifest)
        .await
        .map_err(|e| CogniaError::Plugin(format!("Failed to write plugin.toml: {}", e)))?;
    files_created.push("plugin.toml".to_string());

    // Generate locale files
    let locales_dir = plugin_dir.join("locales");
    tokio::fs::create_dir_all(&locales_dir)
        .await
        .map_err(|e| CogniaError::Plugin(format!("Failed to create locales dir: {}", e)))?;

    let en_json = serde_json::json!({
        "toolName": format!("{} Tool", config.name),
        "toolDesc": format!("A tool provided by {}", config.name),
        "greeting": "Hello from {name}!",
    });
    tokio::fs::write(
        locales_dir.join("en.json"),
        serde_json::to_string_pretty(&en_json).unwrap(),
    )
    .await
    .map_err(|e| CogniaError::Plugin(format!("Failed to write en.json: {}", e)))?;
    files_created.push("locales/en.json".to_string());

    let zh_json = serde_json::json!({
        "toolName": format!("{} 工具", config.name),
        "toolDesc": format!("由 {} 提供的工具", config.name),
        "greeting": "你好，来自 {name}！",
    });
    tokio::fs::write(
        locales_dir.join("zh.json"),
        serde_json::to_string_pretty(&zh_json).unwrap(),
    )
    .await
    .map_err(|e| CogniaError::Plugin(format!("Failed to write zh.json: {}", e)))?;
    files_created.push("locales/zh.json".to_string());

    // Generate .gitignore
    let gitignore = "target/\nnode_modules/\ndist/\n.tools/\n*.wasm\n";
    tokio::fs::write(plugin_dir.join(".gitignore"), gitignore)
        .await
        .map_err(|e| CogniaError::Plugin(format!("Failed to write .gitignore: {}", e)))?;
    files_created.push(".gitignore".to_string());

    // Generate CHANGELOG.md for immediate contributor onboarding
    let changelog = "# Changelog\n\n## 0.1.0\n- Initial scaffold generated by CogniaLauncher.\n";
    tokio::fs::write(plugin_dir.join("CHANGELOG.md"), changelog)
        .await
        .map_err(|e| CogniaError::Plugin(format!("Failed to write CHANGELOG.md: {}", e)))?;
    files_created.push("CHANGELOG.md".to_string());

    // Optionally generate VSCode workspace defaults
    if config.include_vscode {
        let vscode_dir = plugin_dir.join(".vscode");
        tokio::fs::create_dir_all(&vscode_dir)
            .await
            .map_err(|e| CogniaError::Plugin(format!("Failed to create .vscode dir: {}", e)))?;

        let settings = generate_vscode_settings();
        tokio::fs::write(vscode_dir.join("settings.json"), settings)
            .await
            .map_err(|e| {
                CogniaError::Plugin(format!("Failed to write .vscode/settings.json: {}", e))
            })?;
        files_created.push(".vscode/settings.json".to_string());

        let extensions = generate_vscode_extensions(config);
        tokio::fs::write(vscode_dir.join("extensions.json"), extensions)
            .await
            .map_err(|e| {
                CogniaError::Plugin(format!("Failed to write .vscode/extensions.json: {}", e))
            })?;
        files_created.push(".vscode/extensions.json".to_string());
    }

    // Optionally generate CI workflow skeleton
    if config.include_ci {
        let ci_dir = plugin_dir.join(".github").join("workflows");
        tokio::fs::create_dir_all(&ci_dir)
            .await
            .map_err(|e| {
                CogniaError::Plugin(format!("Failed to create .github/workflows dir: {}", e))
            })?;

        let ci = generate_ci_workflow(config);
        tokio::fs::write(ci_dir.join("ci.yml"), ci)
            .await
            .map_err(|e| {
                CogniaError::Plugin(format!("Failed to write .github/workflows/ci.yml: {}", e))
            })?;
        files_created.push(".github/workflows/ci.yml".to_string());
    }

    // Generate language-specific files
    match config.language {
        PluginLanguage::Rust => {
            let extra = generate_rust_project(config, &plugin_dir).await?;
            files_created.extend(extra);
        }
        PluginLanguage::JavaScript => {
            let extra = generate_js_project(config, &plugin_dir).await?;
            files_created.extend(extra);
        }
        PluginLanguage::TypeScript => {
            let extra = generate_ts_project(config, &plugin_dir).await?;
            files_created.extend(extra);
        }
    }

    // Generate README.md
    let readme = generate_readme(config);
    tokio::fs::write(plugin_dir.join("README.md"), &readme)
        .await
        .map_err(|e| CogniaError::Plugin(format!("Failed to write README.md: {}", e)))?;
    files_created.push("README.md".to_string());

    Ok(ScaffoldResult {
        plugin_dir: plugin_dir.display().to_string(),
        files_created,
    })
}

/// Validate a plugin directory
pub async fn validate_plugin(path: &Path) -> CogniaResult<ValidationResult> {
    let mut errors = Vec::new();
    let mut warnings = Vec::new();

    // Check plugin.toml exists
    let manifest_path = path.join("plugin.toml");
    if !manifest_path.exists() {
        errors.push("Missing plugin.toml manifest file".to_string());
        return Ok(ValidationResult {
            valid: false,
            errors,
            warnings,
        });
    }

    // Parse manifest
    match crate::plugin::manifest::PluginManifest::from_file(&manifest_path) {
        Ok(manifest) => {
            // Check WASM file
            let wasm_path = path.join("plugin.wasm");
            if !wasm_path.exists() {
                warnings.push("No plugin.wasm found — plugin needs to be built first".to_string());
            }

            // Validate plugin id format
            if manifest.plugin.id.contains(' ') {
                errors.push("Plugin ID must not contain spaces".to_string());
            }

            // Check version format
            if manifest.plugin.version.is_empty() {
                errors.push("Plugin version is empty".to_string());
            }

            // Check tools have entries
            for tool in &manifest.tools {
                if tool.entry.is_empty() {
                    errors.push(format!("Tool '{}' has empty entry function", tool.id));
                }
                if tool.name_en.is_empty() {
                    errors.push(format!("Tool '{}' has empty English name", tool.id));
                }
            }

            // Check locales
            let locales_dir = path.join("locales");
            if !locales_dir.exists() && manifest.locales.is_empty() {
                warnings.push("No locales found — plugin won't have i18n support".to_string());
            }

            // Check UI configuration for iframe-mode tools
            let has_iframe = manifest
                .tools
                .iter()
                .any(|t| t.ui_mode == crate::plugin::manifest::UiMode::Iframe);
            if has_iframe {
                if let Some(ref ui_config) = manifest.ui {
                    let ui_entry = path.join(&ui_config.entry);
                    if !ui_entry.exists() {
                        warnings.push(format!(
                            "UI entry file '{}' not found — iframe tools won't work until created",
                            ui_config.entry
                        ));
                    }
                }
            }

            // Warn about dangerous permissions
            if manifest.permissions.config_write {
                warnings.push(
                    "Plugin requests config_write (dangerous, requires explicit user grant)"
                        .to_string(),
                );
            }
            if manifest.permissions.pkg_install {
                warnings.push(
                    "Plugin requests pkg_install (dangerous, requires explicit user grant)"
                        .to_string(),
                );
            }
            if manifest.permissions.process_exec {
                warnings.push(
                    "Plugin requests process_exec (dangerous, requires explicit user grant)"
                        .to_string(),
                );
            }
        }
        Err(e) => {
            errors.push(format!("Invalid plugin.toml: {}", e));
        }
    }

    Ok(ValidationResult {
        valid: errors.is_empty(),
        errors,
        warnings,
    })
}

fn validate_scaffold_config(config: &ScaffoldConfig) -> CogniaResult<()> {
    if config.name.trim().is_empty() {
        return Err(CogniaError::Plugin(
            "Plugin scaffold name must not be empty".to_string(),
        ));
    }

    if config.id.trim().is_empty() {
        return Err(CogniaError::Plugin(
            "Plugin scaffold id must not be empty".to_string(),
        ));
    }

    if config.description.trim().is_empty() {
        return Err(CogniaError::Plugin(
            "Plugin scaffold description must not be empty".to_string(),
        ));
    }

    if config.author.trim().is_empty() {
        return Err(CogniaError::Plugin(
            "Plugin scaffold author must not be empty".to_string(),
        ));
    }

    if config.output_dir.trim().is_empty() {
        return Err(CogniaError::Plugin(
            "Plugin scaffold output_dir must not be empty".to_string(),
        ));
    }

    if !config
        .id
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '.' || c == '-' || c == '_')
    {
        return Err(CogniaError::Plugin(format!(
            "Invalid plugin id '{}': only alphanumeric, '.', '-', '_' are allowed",
            config.id
        )));
    }

    validate_optional_url("repository", config.repository.as_deref())?;
    validate_optional_url("homepage", config.homepage.as_deref())?;

    Ok(())
}

fn validate_optional_url(field: &str, value: Option<&str>) -> CogniaResult<()> {
    if let Some(url) = value.map(|v| v.trim()).filter(|v| !v.is_empty()) {
        if !url.starts_with("http://") && !url.starts_with("https://") {
            return Err(CogniaError::Plugin(format!(
                "Invalid {} URL '{}': must start with http:// or https://",
                field, url
            )));
        }
    }
    Ok(())
}

// ============================================================================
// Template generators
// ============================================================================

fn generate_manifest(config: &ScaffoldConfig) -> String {
    let mut perms = Vec::new();
    if config.permissions.config_read {
        perms.push("config_read = true".to_string());
    }
    if config.permissions.env_read {
        perms.push("env_read = true".to_string());
    }
    if config.permissions.pkg_search {
        perms.push("pkg_search = true".to_string());
    }
    if config.permissions.clipboard {
        perms.push("clipboard = true".to_string());
    }
    if config.permissions.notification {
        perms.push("notification = true".to_string());
    }
    if config.permissions.fs_read {
        perms.push("fs_read = [\"data/*\"]".to_string());
    }
    if config.permissions.fs_write {
        perms.push("fs_write = [\"data/*\"]".to_string());
    }
    if config.permissions.process_exec {
        perms.push("process_exec = true".to_string());
    }
    if !config.permissions.http.is_empty() {
        let domains: Vec<String> = config
            .permissions
            .http
            .iter()
            .map(|d| format!("\"{}\"", d))
            .collect();
        perms.push(format!("http = [{}]", domains.join(", ")));
    }

    let entry_fn = config.id.replace(['.', '-'], "_");
    let tool_id = config.id.split('.').last().unwrap_or(&config.id).to_string();
    let keywords = build_keywords(&tool_id, &config.additional_keywords);
    let metadata = build_optional_plugin_metadata(config);

    format!(
        r#"[plugin]
id = "{id}"
name = "{name}"
version = "0.1.0"
description = "{desc}"
authors = ["{author}"]
{metadata}

[[tools]]
id = "{tool_id}"
name_en = "{name} Tool"
name_zh = "{name} 工具"
description_en = "{desc}"
description_zh = "{desc}"
category = "developer"
keywords = [{keywords}]
icon = "Wrench"
entry = "{entry}"

[permissions]
{perms}
"#,
        id = escape_toml_string(&config.id),
        name = escape_toml_string(&config.name),
        desc = escape_toml_string(&config.description),
        author = escape_toml_string(&config.author),
        metadata = metadata,
        tool_id = escape_toml_string(&tool_id),
        keywords = keywords,
        entry = entry_fn,
        perms = perms.join("\n"),
    )
}

fn build_optional_plugin_metadata(config: &ScaffoldConfig) -> String {
    let mut lines = Vec::new();
    if let Some(license) = config.license.as_deref().map(str::trim).filter(|v| !v.is_empty()) {
        lines.push(format!("license = \"{}\"", escape_toml_string(license)));
    }
    if let Some(repository) = config
        .repository
        .as_deref()
        .map(str::trim)
        .filter(|v| !v.is_empty())
    {
        lines.push(format!(
            "repository = \"{}\"",
            escape_toml_string(repository)
        ));
    }
    if let Some(homepage) = config
        .homepage
        .as_deref()
        .map(str::trim)
        .filter(|v| !v.is_empty())
    {
        lines.push(format!("homepage = \"{}\"", escape_toml_string(homepage)));
    }

    if lines.is_empty() {
        String::new()
    } else {
        format!("{}\n", lines.join("\n"))
    }
}

fn build_keywords(base_tool_id: &str, extras: &[String]) -> String {
    let mut values = vec![base_tool_id.trim().to_string()];
    for kw in extras {
        let trimmed = kw.trim();
        if trimmed.is_empty() {
            continue;
        }
        if !values.iter().any(|existing| existing == trimmed) {
            values.push(trimmed.to_string());
        }
    }

    values
        .into_iter()
        .map(|v| format!("\"{}\"", escape_toml_string(&v)))
        .collect::<Vec<String>>()
        .join(", ")
}

fn escape_toml_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn generate_vscode_settings() -> &'static str {
    r#"{
  "editor.formatOnSave": true,
  "files.trimTrailingWhitespace": true,
  "files.insertFinalNewline": true
}
"#
}

fn generate_vscode_extensions(config: &ScaffoldConfig) -> String {
    let mut recommendations = vec![
        "EditorConfig.EditorConfig".to_string(),
        "esbenp.prettier-vscode".to_string(),
    ];
    match config.language {
        PluginLanguage::Rust => {
            recommendations.push("rust-lang.rust-analyzer".to_string());
        }
        PluginLanguage::JavaScript => {
            recommendations.push("dbaeumer.vscode-eslint".to_string());
        }
        PluginLanguage::TypeScript => {
            recommendations.push("dbaeumer.vscode-eslint".to_string());
            recommendations.push("ms-vscode.vscode-typescript-next".to_string());
        }
    }

    serde_json::json!({
        "recommendations": recommendations
    })
    .to_string()
}

fn generate_ci_workflow(config: &ScaffoldConfig) -> String {
    let build_step = match config.language {
        PluginLanguage::Rust => {
            r#"      - name: Install wasm target
        run: rustup target add wasm32-unknown-unknown
      - name: Build
        run: cargo build --target wasm32-unknown-unknown --release"#
        }
        PluginLanguage::JavaScript | PluginLanguage::TypeScript => {
            r#"      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build"#
        }
    };

    format!(
        r#"name: plugin-ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
{build_step}
"#
    )
}

async fn generate_rust_project(
    config: &ScaffoldConfig,
    plugin_dir: &Path,
) -> CogniaResult<Vec<String>> {
    let mut files = Vec::new();

    // Cargo.toml
    let cargo_toml = format!(
        r#"[package]
name = "{}"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
cognia-plugin-sdk = {{ git = "https://github.com/AstroAir/CogniaLauncher", path = "plugin-sdk" }}
extism-pdk = "1.3"
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
"#,
        config.id.replace('.', "-"),
    );
    tokio::fs::write(plugin_dir.join("Cargo.toml"), &cargo_toml)
        .await
        .map_err(|e| CogniaError::Plugin(format!("Failed to write Cargo.toml: {}", e)))?;
    files.push("Cargo.toml".to_string());

    // .cargo/config.toml
    let cargo_dir = plugin_dir.join(".cargo");
    tokio::fs::create_dir_all(&cargo_dir)
        .await
        .map_err(|e| CogniaError::Plugin(format!("Failed to create .cargo dir: {}", e)))?;
    let cargo_config = r#"[build]
target = "wasm32-unknown-unknown"
"#;
    tokio::fs::write(cargo_dir.join("config.toml"), cargo_config)
        .await
        .map_err(|e| CogniaError::Plugin(format!("Failed to write .cargo/config.toml: {}", e)))?;
    files.push(".cargo/config.toml".to_string());

    // src/lib.rs
    let src_dir = plugin_dir.join("src");
    tokio::fs::create_dir_all(&src_dir)
        .await
        .map_err(|e| CogniaError::Plugin(format!("Failed to create src dir: {}", e)))?;

    let entry_fn = config.id.replace(['.', '-'], "_");
    let lib_rs = format!(
        r#"use cognia_plugin_sdk::prelude::*;

#[plugin_fn]
pub fn {entry}(input: String) -> FnResult<String> {{
    // Get platform information
    let platform = cognia::platform::info()?;
    cognia::log::info(&format!("Plugin running on {{}} {{}}", platform.os, platform.arch))?;

    // Get current locale and translate a greeting
    let greeting = cognia::i18n::translate("greeting", &[("name", &platform.hostname)])?;

    // Return JSON result
    Ok(serde_json::json!({{
        "greeting": greeting,
        "platform": platform.os,
        "input": input,
    }}).to_string())
}}
"#,
        entry = entry_fn,
    );
    tokio::fs::write(src_dir.join("lib.rs"), &lib_rs)
        .await
        .map_err(|e| CogniaError::Plugin(format!("Failed to write src/lib.rs: {}", e)))?;
    files.push("src/lib.rs".to_string());

    Ok(files)
}

async fn generate_js_project(
    config: &ScaffoldConfig,
    plugin_dir: &Path,
) -> CogniaResult<Vec<String>> {
    let mut files = Vec::new();

    // package.json
    let package_json = serde_json::json!({
        "name": config.id,
        "version": "0.1.0",
        "description": config.description,
        "author": config.author,
        "scripts": {
            "build": "node scripts/build.mjs",
            "setup:toolchain": "node scripts/build.mjs --setup-only"
        },
        "devDependencies": {
            "@extism/js-pdk": "^1.1.1"
        }
    });
    tokio::fs::write(
        plugin_dir.join("package.json"),
        serde_json::to_string_pretty(&package_json).unwrap(),
    )
    .await
    .map_err(|e| CogniaError::Plugin(format!("Failed to write package.json: {}", e)))?;
    files.push("package.json".to_string());

    // scripts/build.mjs
    let scripts_dir = plugin_dir.join("scripts");
    tokio::fs::create_dir_all(&scripts_dir)
        .await
        .map_err(|e| CogniaError::Plugin(format!("Failed to create scripts dir: {}", e)))?;
    let build_script = generate_wasm_build_script(false, false);
    tokio::fs::write(scripts_dir.join("build.mjs"), &build_script)
        .await
        .map_err(|e| CogniaError::Plugin(format!("Failed to write scripts/build.mjs: {}", e)))?;
    files.push("scripts/build.mjs".to_string());

    // src/index.js
    let src_dir = plugin_dir.join("src");
    tokio::fs::create_dir_all(&src_dir)
        .await
        .map_err(|e| CogniaError::Plugin(format!("Failed to create src dir: {}", e)))?;

    let entry_fn = config.id.replace(['.', '-'], "_");
    let index_js = format!(
        r#"// {name} - CogniaLauncher Plugin (JavaScript)

function {entry}() {{
    const input = Host.inputString();

    // Call host function: get platform info
    const platformJson = Host.getFunctions().cognia_platform_info("");
    const platform = JSON.parse(platformJson);

    // Call host function: log
    Host.getFunctions().cognia_log(JSON.stringify({{
        level: "info",
        message: "Plugin running on " + platform.os
    }}));

    // Return result
    Host.outputString(JSON.stringify({{
        greeting: "Hello from {name}!",
        platform: platform.os,
        input: input,
    }}));
}}

module.exports = {{ {entry} }};
"#,
        name = config.name,
        entry = entry_fn,
    );
    tokio::fs::write(src_dir.join("index.js"), &index_js)
        .await
        .map_err(|e| CogniaError::Plugin(format!("Failed to write src/index.js: {}", e)))?;
    files.push("src/index.js".to_string());

    Ok(files)
}

async fn generate_ts_project(
    config: &ScaffoldConfig,
    plugin_dir: &Path,
) -> CogniaResult<Vec<String>> {
    let mut files = Vec::new();

    // package.json
    let package_json = serde_json::json!({
        "name": config.id,
        "version": "0.1.0",
        "description": config.description,
        "author": config.author,
        "scripts": {
            "build": "node scripts/build.mjs",
            "bundle": "node esbuild.config.mjs",
            "setup:toolchain": "node scripts/build.mjs --setup-only"
        },
        "dependencies": {
            "@cognia/plugin-sdk": "workspace:*"
        },
        "devDependencies": {
            "@extism/js-pdk": "^1.1.1",
            "esbuild": "^0.20.0"
        }
    });
    tokio::fs::write(
        plugin_dir.join("package.json"),
        serde_json::to_string_pretty(&package_json).unwrap(),
    )
    .await
    .map_err(|e| CogniaError::Plugin(format!("Failed to write package.json: {}", e)))?;
    files.push("package.json".to_string());

    // tsconfig.json
    let tsconfig = serde_json::json!({
        "compilerOptions": {
            "target": "es2020",
            "module": "commonjs",
            "lib": [],
            "types": ["@extism/js-pdk"],
            "strict": true,
            "esModuleInterop": true,
            "skipLibCheck": true,
            "noEmit": true
        },
        "include": ["src/**/*.ts", "plugin.d.ts", "node_modules/@cognia/plugin-sdk/cognia.d.ts"]
    });
    tokio::fs::write(
        plugin_dir.join("tsconfig.json"),
        serde_json::to_string_pretty(&tsconfig).unwrap(),
    )
    .await
    .map_err(|e| CogniaError::Plugin(format!("Failed to write tsconfig.json: {}", e)))?;
    files.push("tsconfig.json".to_string());

    // esbuild.config.mjs
    let esbuild_config = r#"import { build } from 'esbuild';

await build({
  entryPoints: ['src/index.ts'],
  bundle: true,
  outfile: 'dist/plugin.js',
  format: 'cjs',
  target: 'es2020',
  platform: 'neutral',
  mainFields: ['main', 'module'],
  external: [],
});
"#;
    tokio::fs::write(plugin_dir.join("esbuild.config.mjs"), esbuild_config)
        .await
        .map_err(|e| CogniaError::Plugin(format!("Failed to write esbuild.config.mjs: {}", e)))?;
    files.push("esbuild.config.mjs".to_string());

    // scripts/build.mjs
    let scripts_dir = plugin_dir.join("scripts");
    tokio::fs::create_dir_all(&scripts_dir)
        .await
        .map_err(|e| CogniaError::Plugin(format!("Failed to create scripts dir: {}", e)))?;
    let build_script = generate_wasm_build_script(true, true);
    tokio::fs::write(scripts_dir.join("build.mjs"), &build_script)
        .await
        .map_err(|e| CogniaError::Plugin(format!("Failed to write scripts/build.mjs: {}", e)))?;
    files.push("scripts/build.mjs".to_string());

    // plugin.d.ts — Extism export declarations + host function declarations
    let entry_fn = config.id.replace(['.', '-'], "_");
    let plugin_dts = format!(
        r#"declare module "main" {{
  export function {entry}(): I32;
}}

declare module "extism:host" {{
  interface user {{
    cognia_config_get(ptr: I64): I64;
    cognia_config_set(ptr: I64): I64;
    cognia_env_list(ptr: I64): I64;
    cognia_provider_list(ptr: I64): I64;
    cognia_env_detect(ptr: I64): I64;
    cognia_env_get_current(ptr: I64): I64;
    cognia_env_list_versions(ptr: I64): I64;
    cognia_env_install_version(ptr: I64): I64;
    cognia_env_set_version(ptr: I64): I64;
    cognia_pkg_search(ptr: I64): I64;
    cognia_pkg_info(ptr: I64): I64;
    cognia_pkg_versions(ptr: I64): I64;
    cognia_pkg_dependencies(ptr: I64): I64;
    cognia_pkg_list_installed(ptr: I64): I64;
    cognia_pkg_check_updates(ptr: I64): I64;
    cognia_pkg_install(ptr: I64): I64;
    cognia_pkg_uninstall(ptr: I64): I64;
    cognia_fs_read(ptr: I64): I64;
    cognia_fs_write(ptr: I64): I64;
    cognia_fs_list_dir(ptr: I64): I64;
    cognia_fs_exists(ptr: I64): I64;
    cognia_fs_delete(ptr: I64): I64;
    cognia_fs_mkdir(ptr: I64): I64;
    cognia_http_get(ptr: I64): I64;
    cognia_http_post(ptr: I64): I64;
    cognia_clipboard_read(ptr: I64): I64;
    cognia_clipboard_write(ptr: I64): I64;
    cognia_notification_send(ptr: I64): I64;
    cognia_process_exec(ptr: I64): I64;
    cognia_get_locale(ptr: I64): I64;
    cognia_i18n_translate(ptr: I64): I64;
    cognia_i18n_get_all(ptr: I64): I64;
    cognia_platform_info(ptr: I64): I64;
    cognia_cache_info(ptr: I64): I64;
    cognia_log(ptr: I64): I64;
    cognia_event_emit(ptr: I64): I64;
    cognia_get_plugin_id(ptr: I64): I64;
  }}
}}
"#,
        entry = entry_fn,
    );
    tokio::fs::write(plugin_dir.join("plugin.d.ts"), &plugin_dts)
        .await
        .map_err(|e| CogniaError::Plugin(format!("Failed to write plugin.d.ts: {}", e)))?;
    files.push("plugin.d.ts".to_string());

    // src/index.ts — main plugin source
    let src_dir = plugin_dir.join("src");
    tokio::fs::create_dir_all(&src_dir)
        .await
        .map_err(|e| CogniaError::Plugin(format!("Failed to create src dir: {}", e)))?;

    let index_ts = format!(
        r#"// {name} - CogniaLauncher Plugin (TypeScript)
import {{ cognia }} from '@cognia/plugin-sdk';

function {entry}(): number {{
    const input = Host.inputString();

    // Get platform information
    const platform = cognia.platform.info();
    cognia.log.info(`Plugin running on ${{platform.os}} ${{platform.arch}}`);

    // Get current locale and translate a greeting
    const greeting = cognia.i18n.translate('greeting', {{ name: platform.hostname }});

    // Return JSON result
    Host.outputString(JSON.stringify({{
        greeting,
        platform: platform.os,
        input,
    }}));
    return 0;
}}

module.exports = {{ {entry} }};
"#,
        name = config.name,
        entry = entry_fn,
    );
    tokio::fs::write(src_dir.join("index.ts"), &index_ts)
        .await
        .map_err(|e| CogniaError::Plugin(format!("Failed to write src/index.ts: {}", e)))?;
    files.push("src/index.ts".to_string());

    Ok(files)
}

fn generate_wasm_build_script(with_bundle: bool, with_interface: bool) -> String {
    let template = include_str!("templates/wasm_build_script.mjs");
    template
        .replace("__WITH_BUNDLE__", if with_bundle { "true" } else { "false" })
        .replace(
            "__WITH_INTERFACE__",
            if with_interface { "true" } else { "false" },
        )
}

fn generate_readme(config: &ScaffoldConfig) -> String {
    let build_instructions = match config.language {
        PluginLanguage::Rust => r#"## Build

```bash
# Install WASM target (first time only)
rustup target add wasm32-unknown-unknown

# Build the plugin
cargo build --release

# The plugin.wasm will be at target/wasm32-unknown-unknown/release/<name>.wasm
# Copy it to plugin.wasm in the project root
cp target/wasm32-unknown-unknown/release/*.wasm plugin.wasm
```"#
            .to_string(),
        PluginLanguage::JavaScript => r#"## Build

```bash
# Install dependencies
pnpm install

# Optional: pre-download extism-js + binaryen into .tools/
pnpm setup:toolchain

# Build the plugin
pnpm build
```

If your environment cannot access GitHub directly:

```bash
EXTISM_JS_PATH=/path/to/extism-js BINARYEN_BIN=/path/to/binaryen/bin pnpm build
```"#
            .to_string(),
        PluginLanguage::TypeScript => r#"## Build

```bash
# Install dependencies
pnpm install

# Optional: pre-download extism-js + binaryen into .tools/
pnpm setup:toolchain

# Bundle TypeScript and compile to WASM
pnpm build
```

If your environment cannot access GitHub directly:

```bash
EXTISM_JS_PATH=/path/to/extism-js BINARYEN_BIN=/path/to/binaryen/bin pnpm build
```"#
            .to_string(),
    };

    let mut project_links = String::new();
    if let Some(repository) = config
        .repository
        .as_deref()
        .map(str::trim)
        .filter(|v| !v.is_empty())
    {
        project_links.push_str(&format!("- Repository: {}\n", repository));
    }
    if let Some(homepage) = config
        .homepage
        .as_deref()
        .map(str::trim)
        .filter(|v| !v.is_empty())
    {
        project_links.push_str(&format!("- Homepage: {}\n", homepage));
    }

    let project_links_section = if project_links.is_empty() {
        String::new()
    } else {
        format!("\n## Project Links\n\n{}", project_links)
    };

    let development_section = format!(
        r#"
## Development Extras

- VSCode defaults: {}
- CI workflow scaffold: {}
"#,
        if config.include_vscode {
            "included (`.vscode/`)"
        } else {
            "not included"
        },
        if config.include_ci {
            "included (`.github/workflows/ci.yml`)"
        } else {
            "not included"
        }
    );

    format!(
        r#"# {name}

{desc}

{build}

## Install

Copy this entire directory into CogniaLauncher's plugins folder, or use the
"Install Plugin" button in the Toolbox > Plugins page.

## Permissions

This plugin uses the following permissions (declared in `plugin.toml`):
- See `[permissions]` section in `plugin.toml`

## Locales

Translation files are in the `locales/` directory:
- `locales/en.json` — English
- `locales/zh.json` — Chinese
{project_links_section}
{development_section}
"#,
        name = config.name,
        desc = config.description,
        build = build_instructions,
        project_links_section = project_links_section,
        development_section = development_section,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_manifest() {
        let config = ScaffoldConfig {
            name: "Test Plugin".to_string(),
            id: "com.example.test".to_string(),
            description: "A test plugin".to_string(),
            author: "Test Author".to_string(),
            output_dir: "/tmp".to_string(),
            license: Some("MIT".to_string()),
            repository: Some("https://github.com/example/test-plugin".to_string()),
            homepage: Some("https://example.com/test-plugin".to_string()),
            language: PluginLanguage::Rust,
            permissions: ScaffoldPermissions {
                config_read: true,
                env_read: true,
                ..Default::default()
            },
            include_ci: true,
            include_vscode: true,
            additional_keywords: vec!["utility".to_string(), "rust".to_string()],
        };
        let manifest = generate_manifest(&config);
        assert!(manifest.contains("id = \"com.example.test\""));
        assert!(manifest.contains("config_read = true"));
        assert!(manifest.contains("env_read = true"));
        assert!(manifest.contains("entry = \"com_example_test\""));
        assert!(manifest.contains("license = \"MIT\""));
        assert!(manifest.contains("repository = \"https://github.com/example/test-plugin\""));
        assert!(manifest.contains("homepage = \"https://example.com/test-plugin\""));
        assert!(manifest.contains("keywords = [\"test\", \"utility\", \"rust\"]"));
    }

    #[test]
    fn test_scaffold_config_default_language() {
        let json = r#"{"name":"T","id":"t","description":"d","author":"a","outputDir":"/tmp"}"#;
        let config: ScaffoldConfig = serde_json::from_str(json).unwrap();
        assert!(matches!(config.language, PluginLanguage::Rust));
        assert!(config.include_vscode);
        assert!(!config.include_ci);
        assert!(config.additional_keywords.is_empty());
    }

    #[test]
    fn test_generate_readme_rust() {
        let config = ScaffoldConfig {
            name: "My Plugin".to_string(),
            id: "com.example.my".to_string(),
            description: "desc".to_string(),
            author: "auth".to_string(),
            output_dir: "/tmp".to_string(),
            license: None,
            repository: None,
            homepage: None,
            language: PluginLanguage::Rust,
            permissions: ScaffoldPermissions::default(),
            include_ci: false,
            include_vscode: true,
            additional_keywords: Vec::new(),
        };
        let readme = generate_readme(&config);
        assert!(readme.contains("# My Plugin"));
        assert!(readme.contains("cargo build"));
    }

    #[test]
    fn test_scaffold_config_typescript_language() {
        let json = r#"{"name":"T","id":"t","description":"d","author":"a","outputDir":"/tmp","language":"typescript"}"#;
        let config: ScaffoldConfig = serde_json::from_str(json).unwrap();
        matches!(config.language, PluginLanguage::TypeScript);
    }

    #[test]
    fn test_generate_readme_ts() {
        let config = ScaffoldConfig {
            name: "TS Plugin".to_string(),
            id: "com.example.ts".to_string(),
            description: "desc".to_string(),
            author: "auth".to_string(),
            output_dir: "/tmp".to_string(),
            license: None,
            repository: None,
            homepage: None,
            language: PluginLanguage::TypeScript,
            permissions: ScaffoldPermissions::default(),
            include_ci: false,
            include_vscode: true,
            additional_keywords: Vec::new(),
        };
        let readme = generate_readme(&config);
        assert!(readme.contains("pnpm build"));
        assert!(readme.contains("TypeScript"));
    }

    #[test]
    fn test_generate_readme_js() {
        let config = ScaffoldConfig {
            name: "JS Plugin".to_string(),
            id: "com.example.js".to_string(),
            description: "desc".to_string(),
            author: "auth".to_string(),
            output_dir: "/tmp".to_string(),
            license: None,
            repository: None,
            homepage: None,
            language: PluginLanguage::JavaScript,
            permissions: ScaffoldPermissions::default(),
            include_ci: false,
            include_vscode: true,
            additional_keywords: Vec::new(),
        };
        let readme = generate_readme(&config);
        assert!(readme.contains("pnpm build"));
    }

    #[test]
    fn test_scaffold_config_optional_fields_deserialize() {
        let json = r#"{
          "name":"Plugin",
          "id":"com.example.plugin",
          "description":"desc",
          "author":"author",
          "outputDir":"/tmp",
          "license":"MIT",
          "repository":"https://github.com/example/repo",
          "homepage":"https://example.com",
          "includeCi":true,
          "includeVscode":false,
          "additionalKeywords":["foo","bar"]
        }"#;
        let config: ScaffoldConfig = serde_json::from_str(json).unwrap();
        assert_eq!(config.license.as_deref(), Some("MIT"));
        assert_eq!(
            config.repository.as_deref(),
            Some("https://github.com/example/repo")
        );
        assert_eq!(config.homepage.as_deref(), Some("https://example.com"));
        assert!(config.include_ci);
        assert!(!config.include_vscode);
        assert_eq!(config.additional_keywords, vec!["foo", "bar"]);
    }

    #[test]
    fn test_validate_scaffold_config_rejects_invalid_url() {
        let config = ScaffoldConfig {
            name: "Test".to_string(),
            id: "com.example.test".to_string(),
            description: "desc".to_string(),
            author: "auth".to_string(),
            output_dir: "/tmp".to_string(),
            license: None,
            repository: Some("github.com/example".to_string()),
            homepage: None,
            language: PluginLanguage::Rust,
            permissions: ScaffoldPermissions::default(),
            include_ci: false,
            include_vscode: true,
            additional_keywords: Vec::new(),
        };
        let result = validate_scaffold_config(&config);
        assert!(result.is_err());
    }

    #[test]
    fn test_generate_wasm_build_script_replaces_flags() {
        let ts_script = generate_wasm_build_script(true, true);
        assert!(ts_script.contains("const WITH_BUNDLE = true;"));
        assert!(ts_script.contains("const WITH_INTERFACE = true;"));
        assert!(!ts_script.contains("__WITH_BUNDLE__"));
        assert!(!ts_script.contains("__WITH_INTERFACE__"));

        let js_script = generate_wasm_build_script(false, false);
        assert!(js_script.contains("const WITH_BUNDLE = false;"));
        assert!(js_script.contains("const WITH_INTERFACE = false;"));
    }
}
