import { renderHook, act, waitFor } from '@testing-library/react';
import { useBackup } from './use-backup';

const mockBackupCreate = jest.fn();
const mockBackupRestore = jest.fn();
const mockBackupList = jest.fn();
const mockBackupDelete = jest.fn();
const mockBackupValidate = jest.fn();
const mockBackupExport = jest.fn();
const mockBackupImport = jest.fn();
const mockBackupCleanup = jest.fn();
const mockDbIntegrityCheck = jest.fn();
const mockDbGetInfo = jest.fn();
const mockIsTauri = jest.fn(() => true);

jest.mock('@/lib/tauri', () => ({
  isTauri: (...args: unknown[]) => mockIsTauri(...args),
  backupCreate: (...args: unknown[]) => mockBackupCreate(...args),
  backupRestore: (...args: unknown[]) => mockBackupRestore(...args),
  backupList: (...args: unknown[]) => mockBackupList(...args),
  backupDelete: (...args: unknown[]) => mockBackupDelete(...args),
  backupValidate: (...args: unknown[]) => mockBackupValidate(...args),
  backupExport: (...args: unknown[]) => mockBackupExport(...args),
  backupImport: (...args: unknown[]) => mockBackupImport(...args),
  backupCleanup: (...args: unknown[]) => mockBackupCleanup(...args),
  dbIntegrityCheck: (...args: unknown[]) => mockDbIntegrityCheck(...args),
  dbGetInfo: (...args: unknown[]) => mockDbGetInfo(...args),
}));

describe('useBackup', () => {
  beforeEach(() => {
    jest.clearAllMocks();
    mockIsTauri.mockReturnValue(true);
    mockBackupList.mockResolvedValue([]);
  });

  it('initializes with auto-refresh', async () => {
    const { result } = renderHook(() => useBackup());

    await waitFor(() => {
      expect(result.current.loading).toBe(false);
    });

    expect(result.current.backups).toEqual([]);
    expect(result.current.error).toBeNull();
    expect(mockBackupList).toHaveBeenCalledTimes(1);
  });

  it('returns normalized create result and reconciles state', async () => {
    mockBackupCreate.mockResolvedValue({
      success: true,
      status: 'partial',
      reasonCode: 'backup_partial_content_failure',
      issues: [{ code: 'content_backup_failed', message: 'config failed', contentType: 'config' }],
      path: '/backup/new',
      manifest: { formatVersion: 1, createdAt: '2026-01-01T00:00:00Z', appVersion: '1.0.0', platform: 'test', hostname: 'host', contents: [], fileChecksums: {}, totalSize: 0, note: null, autoGenerated: false },
      durationMs: 20,
      error: '1 content type failed',
    });

    const { result } = renderHook(() => useBackup());

    await waitFor(() => expect(result.current.loading).toBe(false));
    const callsBefore = mockBackupList.mock.calls.length;

    let created;
    await act(async () => {
      created = await result.current.create(['config'], 'note');
    });

    expect(created).toMatchObject({
      status: 'partial',
      reasonCode: 'backup_partial_content_failure',
      success: true,
    });
    expect(mockBackupList.mock.calls.length).toBe(callsBefore + 1);
  });

  it('reconciles after restore failure', async () => {
    mockBackupRestore.mockResolvedValue({
      success: false,
      status: 'failed',
      reasonCode: 'restore_no_content_restored',
      issues: [{ code: 'content_restore_failed', message: 'file missing', contentType: 'config' }],
      restored: [],
      skipped: [{ contentType: 'config', reason: 'file missing' }],
      error: 'restore failed',
    });

    const { result } = renderHook(() => useBackup());
    await waitFor(() => expect(result.current.loading).toBe(false));
    const callsBefore = mockBackupList.mock.calls.length;

    let restored;
    await act(async () => {
      restored = await result.current.restore('/backup1', ['config']);
    });

    expect(restored).toMatchObject({ status: 'failed', success: false });
    expect(mockBackupList.mock.calls.length).toBe(callsBefore + 1);
  });

  it('normalizes delete result and always reconciles', async () => {
    mockBackupDelete.mockResolvedValue({
      success: false,
      status: 'skipped',
      reasonCode: 'backup_not_found',
      issues: [{ code: 'backup_not_found', message: 'missing', contentType: null }],
      deleted: false,
      path: '/missing',
      error: 'missing',
    });

    const { result } = renderHook(() => useBackup());
    await waitFor(() => expect(result.current.loading).toBe(false));
    const callsBefore = mockBackupList.mock.calls.length;

    let deleted;
    await act(async () => {
      deleted = await result.current.remove('/missing');
    });

    expect(deleted).toMatchObject({
      status: 'skipped',
      deleted: false,
      reasonCode: 'backup_not_found',
    });
    expect(mockBackupList.mock.calls.length).toBe(callsBefore + 1);
  });

  it('normalizes cleanup result and reconciles even when no deletions', async () => {
    mockBackupCleanup.mockResolvedValue({
      success: false,
      status: 'skipped',
      reasonCode: 'cleanup_no_backups_deleted',
      issues: [{ code: 'cleanup_no_backups_deleted', message: 'none', contentType: null }],
      deleted: 0,
      maxCount: 5,
      maxAgeDays: 30,
      error: 'none',
    });

    const { result } = renderHook(() => useBackup());
    await waitFor(() => expect(result.current.loading).toBe(false));
    const callsBefore = mockBackupList.mock.calls.length;

    let cleanupResult;
    await act(async () => {
      cleanupResult = await result.current.cleanup(5, 30);
    });

    expect(cleanupResult).toMatchObject({
      status: 'skipped',
      deleted: 0,
      reasonCode: 'cleanup_no_backups_deleted',
    });
    expect(mockBackupList.mock.calls.length).toBe(callsBefore + 1);
  });

  it('deduplicates reconciliation for concurrent mutations', async () => {
    let releaseGate!: () => void;
    const gate = new Promise<void>((resolve) => {
      releaseGate = resolve;
    });

    mockBackupCreate.mockImplementation(async () => {
      await gate;
      return {
        success: true,
        status: 'success',
        reasonCode: null,
        issues: [],
        path: '/backup/new',
        manifest: { formatVersion: 1, createdAt: '2026-01-01T00:00:00Z', appVersion: '1.0.0', platform: 'test', hostname: 'host', contents: [], fileChecksums: {}, totalSize: 0, note: null, autoGenerated: false },
        durationMs: 10,
        error: null,
      };
    });

    mockBackupCleanup.mockImplementation(async () => {
      await gate;
      return {
        success: true,
        status: 'success',
        reasonCode: null,
        issues: [],
        deleted: 2,
        maxCount: 5,
        maxAgeDays: 30,
        error: null,
      };
    });

    const { result } = renderHook(() => useBackup());
    await waitFor(() => expect(result.current.loading).toBe(false));
    const callsBefore = mockBackupList.mock.calls.length;

    const pending = act(async () => {
      await Promise.all([
        result.current.create(['config']),
        result.current.cleanup(5, 30),
      ]);
    });

    await Promise.resolve();
    releaseGate();
    await pending;

    expect(mockBackupList.mock.calls.length).toBe(callsBefore + 1);
  });

  it.each(['success', 'partial', 'skipped', 'failed'] as const)(
    'preserves backend status "%s" in UI mapping',
    async (status) => {
      mockBackupDelete.mockResolvedValue({
        success: status === 'success',
        status,
        reasonCode: status === 'success' ? null : 'test_reason',
        issues: [],
        deleted: status === 'success',
        path: '/backup/x',
        error: status === 'success' ? null : 'status test',
      });

      const { result } = renderHook(() => useBackup());
      await waitFor(() => expect(result.current.loading).toBe(false));

      let deleted;
      await act(async () => {
        deleted = await result.current.remove('/backup/x');
      });

      expect(deleted.status).toBe(status);
    },
  );

  it('returns skipped outcomes when not running in tauri', async () => {
    mockIsTauri.mockReturnValue(false);
    const { result } = renderHook(() => useBackup());

    let created;
    let restored;
    let removed;
    await act(async () => {
      created = await result.current.create(['config']);
      restored = await result.current.restore('/b', ['config']);
      removed = await result.current.remove('/b');
    });

    expect(created).toMatchObject({ status: 'skipped', reasonCode: 'tauri_unavailable' });
    expect(restored).toMatchObject({ status: 'skipped', reasonCode: 'tauri_unavailable' });
    expect(removed).toMatchObject({ status: 'skipped', reasonCode: 'tauri_unavailable' });
  });
});
