'use client';

import { useState, useCallback, useEffect, useRef } from 'react';
import {
  backupCreate,
  backupRestore,
  backupList,
  backupDelete,
  backupValidate,
  backupExport,
  backupImport,
  backupCleanup,
  dbIntegrityCheck,
  dbGetInfo,
  isTauri,
} from '@/lib/tauri';
import type {
  BackupContentType,
  BackupInfo,
  BackupManifest,
  BackupResult,
  RestoreResult,
  BackupValidationResult,
  BackupDeleteResult,
  BackupExportResult,
  BackupImportResult,
  BackupCleanupResult,
  BackupOperationIssue,
  BackupOperationStatus,
  IntegrityCheckResult,
  DatabaseInfo,
} from '@/types/tauri';

interface UseBackupReturn {
  backups: BackupInfo[];
  loading: boolean;
  error: string | null;
  creating: boolean;
  restoring: boolean;
  refresh: () => Promise<void>;
  create: (contents: BackupContentType[], note?: string) => Promise<BackupResult>;
  restore: (backupPath: string, contents: BackupContentType[]) => Promise<RestoreResult>;
  remove: (backupPath: string) => Promise<BackupDeleteResult>;
  validate: (backupPath: string) => Promise<BackupValidationResult>;
  exportBackup: (backupPath: string, destPath: string) => Promise<BackupExportResult>;
  importBackup: (zipPath: string) => Promise<BackupImportResult>;
  cleanup: (maxCount: number, maxAgeDays: number) => Promise<BackupCleanupResult>;
  checkIntegrity: () => Promise<IntegrityCheckResult | null>;
  getDatabaseInfo: () => Promise<DatabaseInfo | null>;
}

type OperationLike = {
  status: BackupOperationStatus;
  reasonCode?: string | null;
  issues?: BackupOperationIssue[];
  error?: string | null;
};

function emptyManifest(): BackupManifest {
  return {
    formatVersion: 1,
    appVersion: '',
    createdAt: new Date().toISOString(),
    platform: 'unknown',
    hostname: 'unknown',
    contents: [],
    fileChecksums: {},
    totalSize: 0,
    note: null,
    autoGenerated: false,
  };
}

function normalizeIssues(issues?: BackupOperationIssue[]): BackupOperationIssue[] {
  return Array.isArray(issues) ? issues : [];
}

function normalizeStatus(
  status: BackupOperationStatus | undefined,
  fallback: BackupOperationStatus,
): BackupOperationStatus {
  return status ?? fallback;
}

function normalizeBackupResult(result: BackupResult): BackupResult {
  return {
    ...result,
    status: normalizeStatus(result.status, result.success ? 'success' : 'failed'),
    reasonCode: result.reasonCode ?? null,
    issues: normalizeIssues(result.issues),
    error: result.error ?? null,
  };
}

function normalizeRestoreResult(result: RestoreResult): RestoreResult {
  const inferredStatus: BackupOperationStatus = result.status
    ? result.status
    : result.success
      ? 'success'
      : result.skipped.length > 0
        ? result.restored.length > 0
          ? 'partial'
          : 'failed'
        : 'failed';

  return {
    ...result,
    status: inferredStatus,
    reasonCode: result.reasonCode ?? null,
    issues: normalizeIssues(result.issues),
    error: result.error ?? null,
  };
}

function normalizeValidationResult(result: BackupValidationResult): BackupValidationResult {
  return {
    ...result,
    status: normalizeStatus(result.status, result.valid ? 'success' : 'failed'),
    reasonCode: result.reasonCode ?? null,
    issues: normalizeIssues(result.issues),
  };
}

function normalizeDeleteResult(result: BackupDeleteResult): BackupDeleteResult {
  return {
    ...result,
    status: normalizeStatus(result.status, result.deleted ? 'success' : 'skipped'),
    reasonCode: result.reasonCode ?? null,
    issues: normalizeIssues(result.issues),
    error: result.error ?? null,
  };
}

function normalizeExportResult(result: BackupExportResult): BackupExportResult {
  return {
    ...result,
    status: normalizeStatus(result.status, result.success ? 'success' : 'failed'),
    reasonCode: result.reasonCode ?? null,
    issues: normalizeIssues(result.issues),
    error: result.error ?? null,
  };
}

function normalizeImportResult(result: BackupImportResult): BackupImportResult {
  return {
    ...result,
    status: normalizeStatus(result.status, result.success ? 'success' : 'failed'),
    reasonCode: result.reasonCode ?? null,
    issues: normalizeIssues(result.issues),
    error: result.error ?? null,
  };
}

function normalizeCleanupResult(result: BackupCleanupResult): BackupCleanupResult {
  return {
    ...result,
    status: normalizeStatus(
      result.status,
      result.deleted > 0 ? 'success' : result.success ? 'success' : 'skipped',
    ),
    reasonCode: result.reasonCode ?? null,
    issues: normalizeIssues(result.issues),
    error: result.error ?? null,
  };
}

function failureIssue(code: string, message: string): BackupOperationIssue {
  return { code, message, contentType: null };
}

function reasonCodeMessage(reasonCode: string | null | undefined): string | null {
  switch (reasonCode) {
    case 'operation_in_progress':
      return 'Another backup operation is in progress. Wait for it to complete and retry.';
    case 'cleanup_policy_unbounded':
      return 'Cleanup skipped because policy is unbounded (max backups and retention are unlimited).';
    case 'restore_safety_backup_failed':
      return 'Restore completed with degraded safety because pre-restore backup failed.';
    case 'backup_create_permission_denied':
    case 'backup_restore_permission_denied':
    case 'backup_delete_permission_denied':
    case 'backup_export_permission_denied':
    case 'backup_import_permission_denied':
    case 'backup_cleanup_permission_denied':
      return 'Operation failed due to insufficient filesystem permissions.';
    case 'backup_create_path_error':
    case 'backup_restore_path_error':
    case 'backup_delete_path_error':
    case 'backup_export_path_error':
    case 'backup_import_path_error':
    case 'backup_cleanup_path_error':
    case 'backup_import_path_conflict':
      return 'Operation failed due to an invalid, missing, or conflicting filesystem path.';
    default:
      return null;
  }
}

function resolveOperationError(result: OperationLike): string | null {
  if (result.status === 'success') return null;
  if (result.error) return result.error;
  const fromReason = reasonCodeMessage(result.reasonCode);
  if (fromReason) return fromReason;
  const fromIssues = result.issues?.[0]?.message ?? null;
  if (fromIssues) return fromIssues;
  return `Backup operation ended with status: ${result.status}`;
}

export function useBackup(): UseBackupReturn {
  const [backups, setBackups] = useState<BackupInfo[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [creating, setCreating] = useState(false);
  const [restoring, setRestoring] = useState(false);
  const reconcilePromiseRef = useRef<Promise<void> | null>(null);

  const refresh = useCallback(async (preserveError = false) => {
    if (!isTauri()) return;
    setLoading(true);
    if (!preserveError) {
      setError(null);
    }
    try {
      const result = await backupList();
      setBackups(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setLoading(false);
    }
  }, []);

  const reconcile = useCallback(async () => {
    if (!isTauri()) return;
    if (reconcilePromiseRef.current) {
      await reconcilePromiseRef.current;
      return;
    }

    const pending = (async () => {
      await refresh(true);
    })();
    reconcilePromiseRef.current = pending;

    try {
      await pending;
    } finally {
      if (reconcilePromiseRef.current === pending) {
        reconcilePromiseRef.current = null;
      }
    }
  }, [refresh]);

  useEffect(() => {
    refresh();
  }, [refresh]);

  const create = useCallback(
    async (contents: BackupContentType[], note?: string): Promise<BackupResult> => {
      if (!isTauri()) {
        return {
          success: false,
          status: 'skipped',
          reasonCode: 'tauri_unavailable',
          issues: [failureIssue('tauri_unavailable', 'Tauri runtime is unavailable')],
          path: '',
          manifest: emptyManifest(),
          durationMs: 0,
          error: 'Tauri runtime is unavailable',
        };
      }
      setCreating(true);
      setError(null);
      try {
        const result = normalizeBackupResult(await backupCreate(contents, note));
        const opError = resolveOperationError(result);
        setError(opError);
        await reconcile();
        return result;
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        setError(msg);
        await reconcile();
        return {
          success: false,
          status: 'failed',
          reasonCode: 'backup_create_failed',
          issues: [failureIssue('backup_create_failed', msg)],
          path: '',
          manifest: emptyManifest(),
          durationMs: 0,
          error: msg,
        };
      } finally {
        setCreating(false);
      }
    },
    [reconcile],
  );

  const restore = useCallback(
    async (backupPath: string, contents: BackupContentType[]): Promise<RestoreResult> => {
      if (!isTauri()) {
        return {
          success: false,
          status: 'skipped',
          reasonCode: 'tauri_unavailable',
          issues: [failureIssue('tauri_unavailable', 'Tauri runtime is unavailable')],
          restored: [],
          skipped: [],
          error: 'Tauri runtime is unavailable',
        };
      }
      setRestoring(true);
      setError(null);
      try {
        const result = normalizeRestoreResult(await backupRestore(backupPath, contents));
        const opError = resolveOperationError(result);
        setError(opError);
        await reconcile();
        return result;
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        setError(msg);
        await reconcile();
        return {
          success: false,
          status: 'failed',
          reasonCode: 'backup_restore_failed',
          issues: [failureIssue('backup_restore_failed', msg)],
          restored: [],
          skipped: [],
          error: msg,
        };
      } finally {
        setRestoring(false);
      }
    },
    [reconcile],
  );

  const remove = useCallback(
    async (backupPath: string): Promise<BackupDeleteResult> => {
      if (!isTauri()) {
        return {
          success: false,
          status: 'skipped',
          reasonCode: 'tauri_unavailable',
          issues: [failureIssue('tauri_unavailable', 'Tauri runtime is unavailable')],
          deleted: false,
          path: backupPath,
          error: 'Tauri runtime is unavailable',
        };
      }
      setError(null);
      try {
        const result = normalizeDeleteResult(await backupDelete(backupPath));
        const opError = resolveOperationError(result);
        setError(opError);
        await reconcile();
        return result;
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        setError(msg);
        await reconcile();
        return {
          success: false,
          status: 'failed',
          reasonCode: 'backup_delete_failed',
          issues: [failureIssue('backup_delete_failed', msg)],
          deleted: false,
          path: backupPath,
          error: msg,
        };
      }
    },
    [reconcile],
  );

  const validateBackup = useCallback(
    async (backupPath: string): Promise<BackupValidationResult> => {
      if (!isTauri()) {
        return {
          valid: false,
          status: 'skipped',
          reasonCode: 'tauri_unavailable',
          issues: [failureIssue('tauri_unavailable', 'Tauri runtime is unavailable')],
          manifest: null,
          missingFiles: [],
          checksumMismatches: [],
          errors: ['Tauri runtime is unavailable'],
        };
      }
      try {
        const result = normalizeValidationResult(await backupValidate(backupPath));
        if (result.errors.length > 0) setError(result.errors.join('; '));
        return result;
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        setError(msg);
        return {
          valid: false,
          status: 'failed',
          reasonCode: 'backup_validate_failed',
          issues: [failureIssue('backup_validate_failed', msg)],
          manifest: null,
          missingFiles: [],
          checksumMismatches: [],
          errors: [msg],
        };
      }
    },
    [],
  );

  const checkIntegrity = useCallback(async (): Promise<IntegrityCheckResult | null> => {
    if (!isTauri()) return null;
    try {
      return await dbIntegrityCheck();
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
      return null;
    }
  }, []);

  const exportBackupFn = useCallback(
    async (backupPath: string, destPath: string): Promise<BackupExportResult> => {
      if (!isTauri()) {
        return {
          success: false,
          status: 'skipped',
          reasonCode: 'tauri_unavailable',
          issues: [failureIssue('tauri_unavailable', 'Tauri runtime is unavailable')],
          bytes: 0,
          backupPath,
          destPath,
          error: 'Tauri runtime is unavailable',
        };
      }
      try {
        const result = normalizeExportResult(await backupExport(backupPath, destPath));
        const opError = resolveOperationError(result);
        setError(opError);
        await reconcile();
        return result;
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        setError(msg);
        await reconcile();
        return {
          success: false,
          status: 'failed',
          reasonCode: 'backup_export_failed',
          issues: [failureIssue('backup_export_failed', msg)],
          bytes: 0,
          backupPath,
          destPath,
          error: msg,
        };
      }
    },
    [reconcile],
  );

  const importBackupFn = useCallback(
    async (zipPath: string): Promise<BackupImportResult> => {
      if (!isTauri()) {
        return {
          success: false,
          status: 'skipped',
          reasonCode: 'tauri_unavailable',
          issues: [failureIssue('tauri_unavailable', 'Tauri runtime is unavailable')],
          zipPath,
          info: null,
          error: 'Tauri runtime is unavailable',
        };
      }
      try {
        const result = normalizeImportResult(await backupImport(zipPath));
        const opError = resolveOperationError(result);
        setError(opError);
        await reconcile();
        return result;
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        setError(msg);
        await reconcile();
        return {
          success: false,
          status: 'failed',
          reasonCode: 'backup_import_failed',
          issues: [failureIssue('backup_import_failed', msg)],
          zipPath,
          info: null,
          error: msg,
        };
      }
    },
    [reconcile],
  );

  const cleanup = useCallback(
    async (maxCount: number, maxAgeDays: number): Promise<BackupCleanupResult> => {
      if (!isTauri()) {
        return {
          success: false,
          status: 'skipped',
          reasonCode: 'tauri_unavailable',
          issues: [failureIssue('tauri_unavailable', 'Tauri runtime is unavailable')],
          deleted: 0,
          maxCount,
          maxAgeDays,
          error: 'Tauri runtime is unavailable',
        };
      }
      try {
        const result = normalizeCleanupResult(await backupCleanup(maxCount, maxAgeDays));
        const opError = resolveOperationError(result);
        setError(opError);
        await reconcile();
        return result;
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        setError(msg);
        await reconcile();
        return {
          success: false,
          status: 'failed',
          reasonCode: 'backup_cleanup_failed',
          issues: [failureIssue('backup_cleanup_failed', msg)],
          deleted: 0,
          maxCount,
          maxAgeDays,
          error: msg,
        };
      }
    },
    [reconcile],
  );

  const getDatabaseInfo = useCallback(async (): Promise<DatabaseInfo | null> => {
    if (!isTauri()) return null;
    try {
      return await dbGetInfo();
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
      return null;
    }
  }, []);

  return {
    backups,
    loading,
    error,
    creating,
    restoring,
    refresh,
    create,
    restore,
    remove,
    validate: validateBackup,
    exportBackup: exportBackupFn,
    importBackup: importBackupFn,
    cleanup,
    checkIntegrity,
    getDatabaseInfo,
  };
}
