# Serena Project Configuration for CogniaLauncher
# React + Tauri desktop application

# Ignore files listed in .gitignore
ignore_all_files_in_gitignore: true

# Additional paths to ignore (gitignore syntax)
ignored_paths:
  - node_modules/**
  - .next/**
  - out/**
  - target/**
  - dist/**

# Read-only mode (set to true to disable editing tools)
read_only: false

# Tools to exclude (empty = all tools enabled)
excluded_tools: []

# Initial prompt for the project
initial_prompt: |
  This is CogniaLauncher, a React + Tauri desktop application.
  Tech stack:
  - Frontend: Next.js 16 (React 19) + TypeScript + Tailwind CSS v4 + shadcn/ui + Zustand
  - Backend: Tauri 2.9 (Rust)
  - Package manager: pnpm

  Key directories:
  - app/ - Next.js App Router pages
  - components/ - React components (ui/ for shadcn components)
  - src-tauri/ - Rust backend code
  - lib/ - Utilities and stores

# Project name
project_name: "CogniaLauncher"

# Programming languages used in this project
languages:
  - typescript
  - rust

# Optional tools to include
included_optional_tools: []

# File encoding
encoding: utf-8
